eureka:
  client:
    serviceUrl:
      defaultZone: http://master:8761/eureka/,http://slave:8762/eureka/
server:
  port: 8401
spring:
  application:
    name: cloud-zuul

zuul:
  ignoredServices: '*'
  routes:
    cloud_feign:
      path: /cloud-feign/**
      serviceId: cloud-feign
      sensitive-headers: "*"
#hystrix的超时时间
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 10000
#ribbon的超时时间
ribbon:
  ReadTimeout: 5000
  ConnectTimeout: 1000
