server:
  port: 8501

spring:
  application:
    name: cloud-feign

eureka:
  client:
    serviceUrl:
      defaultZone: http://master:8761/eureka,http://slave:8762/eureka
feign:
  hystrix:
    enabled: true
#hystrix的超时时间
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 4000
#ribbon的超时时间
ribbon:
  ReadTimeout: 2000
  ConnectTimeout: 1000